### ISSUE TITLE
Conditionally revealing a related question

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [LandRegistry/govuk-frontend-wtf#44]
**Describe the solution you'd like**
Recreate the conditional reveal functionality available with nunjucks:

https://design-system.service.gov.uk/components/radios/#radios-with-conditionally-revealing-content-example-nunjucks

**Comment by andymantell** [comment]
Have put together a demo over at https://github.com/LandRegistry/govuk-frontend-wtf-demo/pull/9

Going to put some comments on it tomorrow to explain the solution and _why_ it works because it's perhaps not immediately obvious how the bits fit together - but the code works as it stands, no changes required to the library.

**Comment by SoumayaMauthoorMOJ** [comment]
Amazing and thanks for the quick turnaround :-) I've closed the issue https://github.com/LandRegistry/govuk-frontend-wtf/issues/44 in the library
